/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-expense`; params?: Router.UnknownInputParams; } | { pathname: `/create-group`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/friends` | `/friends`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/groups` | `/groups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-expense`; params?: Router.UnknownOutputParams; } | { pathname: `/create-group`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/activity` | `/activity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/friends` | `/friends`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/groups` | `/groups`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/group/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-expense${`?${string}` | `#${string}` | ''}` | `/create-group${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/activity${`?${string}` | `#${string}` | ''}` | `/activity${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/friends${`?${string}` | `#${string}` | ''}` | `/friends${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/groups${`?${string}` | `#${string}` | ''}` | `/groups${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-expense`; params?: Router.UnknownInputParams; } | { pathname: `/create-group`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/friends` | `/friends`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/groups` | `/groups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | `/group/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
